import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
export const dynamic = "force-dynamic";
import SvgIcons from "./_icons";
import Header from "./_Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "آژانس دیجیتال مارکتینگ- کدینکس",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SvgIcons />

        <div className="ribbon-top bg-[#7026d4] text-center">
          <div className="container">
            <p className="flex items-center justify-center gap-3 p-3 font-bold">
              کمپین ۴۰ وبیتو
              <a
                href="https://webito.ir/campaign-40/"
                className="bg-[#e7b855] text-sm rounded-full flex w-fit text-black items-center px-4 p-0.5 font-normal"
              >
                جزئیات
              </a>
            </p>
          </div>
        </div>

        <Header />

        {children}
      </body>
    </html>
  );
}
